# CMake generated Testfile for 
# Source directory: /home/jason/Project/PX4/Firmware/platforms/posix
# Build directory: /home/jason/Project/PX4/Firmware/platforms/posix
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(autodeclination "/home/jason/Project/PX4/Firmware/Tools/sitl_run.sh" "/home/jason/Project/PX4/Firmware/bin/px4" "none" "none" "test_autodeclination_generated" "/home/jason/Project/PX4/Firmware" "/home/jason/Project/PX4/Firmware")
set_tests_properties(autodeclination PROPERTIES  FAIL_REGULAR_EXPRESSION "autodeclination FAILED" PASS_REGULAR_EXPRESSION "autodeclination PASSED" WORKING_DIRECTORY "/home/jason/Project/PX4/Firmware/tmp")
add_test(bson "/home/jason/Project/PX4/Firmware/Tools/sitl_run.sh" "/home/jason/Project/PX4/Firmware/bin/px4" "none" "none" "test_bson_generated" "/home/jason/Project/PX4/Firmware" "/home/jason/Project/PX4/Firmware")
set_tests_properties(bson PROPERTIES  FAIL_REGULAR_EXPRESSION "bson FAILED" PASS_REGULAR_EXPRESSION "bson PASSED" WORKING_DIRECTORY "/home/jason/Project/PX4/Firmware/tmp")
add_test(commander "/home/jason/Project/PX4/Firmware/Tools/sitl_run.sh" "/home/jason/Project/PX4/Firmware/bin/px4" "none" "none" "test_commander_generated" "/home/jason/Project/PX4/Firmware" "/home/jason/Project/PX4/Firmware")
set_tests_properties(commander PROPERTIES  FAIL_REGULAR_EXPRESSION "commander FAILED" PASS_REGULAR_EXPRESSION "commander PASSED" WORKING_DIRECTORY "/home/jason/Project/PX4/Firmware/tmp")
add_test(controllib "/home/jason/Project/PX4/Firmware/Tools/sitl_run.sh" "/home/jason/Project/PX4/Firmware/bin/px4" "none" "none" "test_controllib_generated" "/home/jason/Project/PX4/Firmware" "/home/jason/Project/PX4/Firmware")
set_tests_properties(controllib PROPERTIES  FAIL_REGULAR_EXPRESSION "controllib FAILED" PASS_REGULAR_EXPRESSION "controllib PASSED" WORKING_DIRECTORY "/home/jason/Project/PX4/Firmware/tmp")
add_test(conv "/home/jason/Project/PX4/Firmware/Tools/sitl_run.sh" "/home/jason/Project/PX4/Firmware/bin/px4" "none" "none" "test_conv_generated" "/home/jason/Project/PX4/Firmware" "/home/jason/Project/PX4/Firmware")
set_tests_properties(conv PROPERTIES  FAIL_REGULAR_EXPRESSION "conv FAILED" PASS_REGULAR_EXPRESSION "conv PASSED" WORKING_DIRECTORY "/home/jason/Project/PX4/Firmware/tmp")
add_test(ctlmath "/home/jason/Project/PX4/Firmware/Tools/sitl_run.sh" "/home/jason/Project/PX4/Firmware/bin/px4" "none" "none" "test_ctlmath_generated" "/home/jason/Project/PX4/Firmware" "/home/jason/Project/PX4/Firmware")
set_tests_properties(ctlmath PROPERTIES  FAIL_REGULAR_EXPRESSION "ctlmath FAILED" PASS_REGULAR_EXPRESSION "ctlmath PASSED" WORKING_DIRECTORY "/home/jason/Project/PX4/Firmware/tmp")
add_test(dataman "/home/jason/Project/PX4/Firmware/Tools/sitl_run.sh" "/home/jason/Project/PX4/Firmware/bin/px4" "none" "none" "test_dataman_generated" "/home/jason/Project/PX4/Firmware" "/home/jason/Project/PX4/Firmware")
set_tests_properties(dataman PROPERTIES  FAIL_REGULAR_EXPRESSION "dataman FAILED" PASS_REGULAR_EXPRESSION "dataman PASSED" WORKING_DIRECTORY "/home/jason/Project/PX4/Firmware/tmp")
add_test(file2 "/home/jason/Project/PX4/Firmware/Tools/sitl_run.sh" "/home/jason/Project/PX4/Firmware/bin/px4" "none" "none" "test_file2_generated" "/home/jason/Project/PX4/Firmware" "/home/jason/Project/PX4/Firmware")
set_tests_properties(file2 PROPERTIES  FAIL_REGULAR_EXPRESSION "file2 FAILED" PASS_REGULAR_EXPRESSION "file2 PASSED" WORKING_DIRECTORY "/home/jason/Project/PX4/Firmware/tmp")
add_test(float "/home/jason/Project/PX4/Firmware/Tools/sitl_run.sh" "/home/jason/Project/PX4/Firmware/bin/px4" "none" "none" "test_float_generated" "/home/jason/Project/PX4/Firmware" "/home/jason/Project/PX4/Firmware")
set_tests_properties(float PROPERTIES  FAIL_REGULAR_EXPRESSION "float FAILED" PASS_REGULAR_EXPRESSION "float PASSED" WORKING_DIRECTORY "/home/jason/Project/PX4/Firmware/tmp")
add_test(gpio "/home/jason/Project/PX4/Firmware/Tools/sitl_run.sh" "/home/jason/Project/PX4/Firmware/bin/px4" "none" "none" "test_gpio_generated" "/home/jason/Project/PX4/Firmware" "/home/jason/Project/PX4/Firmware")
set_tests_properties(gpio PROPERTIES  FAIL_REGULAR_EXPRESSION "gpio FAILED" PASS_REGULAR_EXPRESSION "gpio PASSED" WORKING_DIRECTORY "/home/jason/Project/PX4/Firmware/tmp")
add_test(hrt "/home/jason/Project/PX4/Firmware/Tools/sitl_run.sh" "/home/jason/Project/PX4/Firmware/bin/px4" "none" "none" "test_hrt_generated" "/home/jason/Project/PX4/Firmware" "/home/jason/Project/PX4/Firmware")
set_tests_properties(hrt PROPERTIES  FAIL_REGULAR_EXPRESSION "hrt FAILED" PASS_REGULAR_EXPRESSION "hrt PASSED" WORKING_DIRECTORY "/home/jason/Project/PX4/Firmware/tmp")
add_test(hysteresis "/home/jason/Project/PX4/Firmware/Tools/sitl_run.sh" "/home/jason/Project/PX4/Firmware/bin/px4" "none" "none" "test_hysteresis_generated" "/home/jason/Project/PX4/Firmware" "/home/jason/Project/PX4/Firmware")
set_tests_properties(hysteresis PROPERTIES  FAIL_REGULAR_EXPRESSION "hysteresis FAILED" PASS_REGULAR_EXPRESSION "hysteresis PASSED" WORKING_DIRECTORY "/home/jason/Project/PX4/Firmware/tmp")
add_test(int "/home/jason/Project/PX4/Firmware/Tools/sitl_run.sh" "/home/jason/Project/PX4/Firmware/bin/px4" "none" "none" "test_int_generated" "/home/jason/Project/PX4/Firmware" "/home/jason/Project/PX4/Firmware")
set_tests_properties(int PROPERTIES  FAIL_REGULAR_EXPRESSION "int FAILED" PASS_REGULAR_EXPRESSION "int PASSED" WORKING_DIRECTORY "/home/jason/Project/PX4/Firmware/tmp")
add_test(mathlib "/home/jason/Project/PX4/Firmware/Tools/sitl_run.sh" "/home/jason/Project/PX4/Firmware/bin/px4" "none" "none" "test_mathlib_generated" "/home/jason/Project/PX4/Firmware" "/home/jason/Project/PX4/Firmware")
set_tests_properties(mathlib PROPERTIES  FAIL_REGULAR_EXPRESSION "mathlib FAILED" PASS_REGULAR_EXPRESSION "mathlib PASSED" WORKING_DIRECTORY "/home/jason/Project/PX4/Firmware/tmp")
add_test(matrix "/home/jason/Project/PX4/Firmware/Tools/sitl_run.sh" "/home/jason/Project/PX4/Firmware/bin/px4" "none" "none" "test_matrix_generated" "/home/jason/Project/PX4/Firmware" "/home/jason/Project/PX4/Firmware")
set_tests_properties(matrix PROPERTIES  FAIL_REGULAR_EXPRESSION "matrix FAILED" PASS_REGULAR_EXPRESSION "matrix PASSED" WORKING_DIRECTORY "/home/jason/Project/PX4/Firmware/tmp")
add_test(microbench_hrt "/home/jason/Project/PX4/Firmware/Tools/sitl_run.sh" "/home/jason/Project/PX4/Firmware/bin/px4" "none" "none" "test_microbench_hrt_generated" "/home/jason/Project/PX4/Firmware" "/home/jason/Project/PX4/Firmware")
set_tests_properties(microbench_hrt PROPERTIES  FAIL_REGULAR_EXPRESSION "microbench_hrt FAILED" PASS_REGULAR_EXPRESSION "microbench_hrt PASSED" WORKING_DIRECTORY "/home/jason/Project/PX4/Firmware/tmp")
add_test(microbench_math "/home/jason/Project/PX4/Firmware/Tools/sitl_run.sh" "/home/jason/Project/PX4/Firmware/bin/px4" "none" "none" "test_microbench_math_generated" "/home/jason/Project/PX4/Firmware" "/home/jason/Project/PX4/Firmware")
set_tests_properties(microbench_math PROPERTIES  FAIL_REGULAR_EXPRESSION "microbench_math FAILED" PASS_REGULAR_EXPRESSION "microbench_math PASSED" WORKING_DIRECTORY "/home/jason/Project/PX4/Firmware/tmp")
add_test(microbench_matrix "/home/jason/Project/PX4/Firmware/Tools/sitl_run.sh" "/home/jason/Project/PX4/Firmware/bin/px4" "none" "none" "test_microbench_matrix_generated" "/home/jason/Project/PX4/Firmware" "/home/jason/Project/PX4/Firmware")
set_tests_properties(microbench_matrix PROPERTIES  FAIL_REGULAR_EXPRESSION "microbench_matrix FAILED" PASS_REGULAR_EXPRESSION "microbench_matrix PASSED" WORKING_DIRECTORY "/home/jason/Project/PX4/Firmware/tmp")
add_test(microbench_uorb "/home/jason/Project/PX4/Firmware/Tools/sitl_run.sh" "/home/jason/Project/PX4/Firmware/bin/px4" "none" "none" "test_microbench_uorb_generated" "/home/jason/Project/PX4/Firmware" "/home/jason/Project/PX4/Firmware")
set_tests_properties(microbench_uorb PROPERTIES  FAIL_REGULAR_EXPRESSION "microbench_uorb FAILED" PASS_REGULAR_EXPRESSION "microbench_uorb PASSED" WORKING_DIRECTORY "/home/jason/Project/PX4/Firmware/tmp")
add_test(mixer "/home/jason/Project/PX4/Firmware/Tools/sitl_run.sh" "/home/jason/Project/PX4/Firmware/bin/px4" "none" "none" "test_mixer_generated" "/home/jason/Project/PX4/Firmware" "/home/jason/Project/PX4/Firmware")
set_tests_properties(mixer PROPERTIES  FAIL_REGULAR_EXPRESSION "mixer FAILED" PASS_REGULAR_EXPRESSION "mixer PASSED" WORKING_DIRECTORY "/home/jason/Project/PX4/Firmware/tmp")
add_test(param "/home/jason/Project/PX4/Firmware/Tools/sitl_run.sh" "/home/jason/Project/PX4/Firmware/bin/px4" "none" "none" "test_param_generated" "/home/jason/Project/PX4/Firmware" "/home/jason/Project/PX4/Firmware")
set_tests_properties(param PROPERTIES  FAIL_REGULAR_EXPRESSION "param FAILED" PASS_REGULAR_EXPRESSION "param PASSED" WORKING_DIRECTORY "/home/jason/Project/PX4/Firmware/tmp")
add_test(parameters "/home/jason/Project/PX4/Firmware/Tools/sitl_run.sh" "/home/jason/Project/PX4/Firmware/bin/px4" "none" "none" "test_parameters_generated" "/home/jason/Project/PX4/Firmware" "/home/jason/Project/PX4/Firmware")
set_tests_properties(parameters PROPERTIES  FAIL_REGULAR_EXPRESSION "parameters FAILED" PASS_REGULAR_EXPRESSION "parameters PASSED" WORKING_DIRECTORY "/home/jason/Project/PX4/Firmware/tmp")
add_test(perf "/home/jason/Project/PX4/Firmware/Tools/sitl_run.sh" "/home/jason/Project/PX4/Firmware/bin/px4" "none" "none" "test_perf_generated" "/home/jason/Project/PX4/Firmware" "/home/jason/Project/PX4/Firmware")
set_tests_properties(perf PROPERTIES  FAIL_REGULAR_EXPRESSION "perf FAILED" PASS_REGULAR_EXPRESSION "perf PASSED" WORKING_DIRECTORY "/home/jason/Project/PX4/Firmware/tmp")
add_test(rc "/home/jason/Project/PX4/Firmware/Tools/sitl_run.sh" "/home/jason/Project/PX4/Firmware/bin/px4" "none" "none" "test_rc_generated" "/home/jason/Project/PX4/Firmware" "/home/jason/Project/PX4/Firmware")
set_tests_properties(rc PROPERTIES  FAIL_REGULAR_EXPRESSION "rc FAILED" PASS_REGULAR_EXPRESSION "rc PASSED" WORKING_DIRECTORY "/home/jason/Project/PX4/Firmware/tmp")
add_test(servo "/home/jason/Project/PX4/Firmware/Tools/sitl_run.sh" "/home/jason/Project/PX4/Firmware/bin/px4" "none" "none" "test_servo_generated" "/home/jason/Project/PX4/Firmware" "/home/jason/Project/PX4/Firmware")
set_tests_properties(servo PROPERTIES  FAIL_REGULAR_EXPRESSION "servo FAILED" PASS_REGULAR_EXPRESSION "servo PASSED" WORKING_DIRECTORY "/home/jason/Project/PX4/Firmware/tmp")
add_test(sf0x "/home/jason/Project/PX4/Firmware/Tools/sitl_run.sh" "/home/jason/Project/PX4/Firmware/bin/px4" "none" "none" "test_sf0x_generated" "/home/jason/Project/PX4/Firmware" "/home/jason/Project/PX4/Firmware")
set_tests_properties(sf0x PROPERTIES  FAIL_REGULAR_EXPRESSION "sf0x FAILED" PASS_REGULAR_EXPRESSION "sf0x PASSED" WORKING_DIRECTORY "/home/jason/Project/PX4/Firmware/tmp")
add_test(sleep "/home/jason/Project/PX4/Firmware/Tools/sitl_run.sh" "/home/jason/Project/PX4/Firmware/bin/px4" "none" "none" "test_sleep_generated" "/home/jason/Project/PX4/Firmware" "/home/jason/Project/PX4/Firmware")
set_tests_properties(sleep PROPERTIES  FAIL_REGULAR_EXPRESSION "sleep FAILED" PASS_REGULAR_EXPRESSION "sleep PASSED" WORKING_DIRECTORY "/home/jason/Project/PX4/Firmware/tmp")
add_test(uorb "/home/jason/Project/PX4/Firmware/Tools/sitl_run.sh" "/home/jason/Project/PX4/Firmware/bin/px4" "none" "none" "test_uorb_generated" "/home/jason/Project/PX4/Firmware" "/home/jason/Project/PX4/Firmware")
set_tests_properties(uorb PROPERTIES  FAIL_REGULAR_EXPRESSION "uorb FAILED" PASS_REGULAR_EXPRESSION "uorb PASSED" WORKING_DIRECTORY "/home/jason/Project/PX4/Firmware/tmp")
add_test(versioning "/home/jason/Project/PX4/Firmware/Tools/sitl_run.sh" "/home/jason/Project/PX4/Firmware/bin/px4" "none" "none" "test_versioning_generated" "/home/jason/Project/PX4/Firmware" "/home/jason/Project/PX4/Firmware")
set_tests_properties(versioning PROPERTIES  FAIL_REGULAR_EXPRESSION "versioning FAILED" PASS_REGULAR_EXPRESSION "versioning PASSED" WORKING_DIRECTORY "/home/jason/Project/PX4/Firmware/tmp")
add_test(mavlink "/home/jason/Project/PX4/Firmware/Tools/sitl_run.sh" "/home/jason/Project/PX4/Firmware/bin/px4" "none" "none" "test_mavlink" "/home/jason/Project/PX4/Firmware" "/home/jason/Project/PX4/Firmware")
set_tests_properties(mavlink PROPERTIES  FAIL_REGULAR_EXPRESSION "mavlink FAILED" PASS_REGULAR_EXPRESSION "mavlink PASSED" WORKING_DIRECTORY "/home/jason/Project/PX4/Firmware/tmp")
add_test(posix_hello "/home/jason/Project/PX4/Firmware/Tools/sitl_run.sh" "/home/jason/Project/PX4/Firmware/bin/px4" "none" "none" "cmd_hello_generated" "/home/jason/Project/PX4/Firmware" "/home/jason/Project/PX4/Firmware")
set_tests_properties(posix_hello PROPERTIES  PASS_REGULAR_EXPRESSION "Shutting down" WORKING_DIRECTORY "/home/jason/Project/PX4/Firmware/tmp")
add_test(posix_hrt_test "/home/jason/Project/PX4/Firmware/Tools/sitl_run.sh" "/home/jason/Project/PX4/Firmware/bin/px4" "none" "none" "cmd_hrt_test_generated" "/home/jason/Project/PX4/Firmware" "/home/jason/Project/PX4/Firmware")
set_tests_properties(posix_hrt_test PROPERTIES  PASS_REGULAR_EXPRESSION "Shutting down" WORKING_DIRECTORY "/home/jason/Project/PX4/Firmware/tmp")
add_test(posix_vcdev_test "/home/jason/Project/PX4/Firmware/Tools/sitl_run.sh" "/home/jason/Project/PX4/Firmware/bin/px4" "none" "none" "cmd_vcdev_test_generated" "/home/jason/Project/PX4/Firmware" "/home/jason/Project/PX4/Firmware")
set_tests_properties(posix_vcdev_test PROPERTIES  PASS_REGULAR_EXPRESSION "Shutting down" WORKING_DIRECTORY "/home/jason/Project/PX4/Firmware/tmp")
add_test(posix_wqueue_test "/home/jason/Project/PX4/Firmware/Tools/sitl_run.sh" "/home/jason/Project/PX4/Firmware/bin/px4" "none" "none" "cmd_wqueue_test_generated" "/home/jason/Project/PX4/Firmware" "/home/jason/Project/PX4/Firmware")
set_tests_properties(posix_wqueue_test PROPERTIES  PASS_REGULAR_EXPRESSION "Shutting down" WORKING_DIRECTORY "/home/jason/Project/PX4/Firmware/tmp")
subdirs("src")
