#!/bin/sh

# PX4 commands need the 'px4-' prefix in bash.
# (px4-alias.sh is expected to be in the PATH)
# px4-alias是将uorb等command添加前缀，变为px4-uorb，然后让bash去执行。因此px4-alias.sh是必须的。

source px4-alias.sh

uorb start

#param load

#param set SYS_AUTOSTART 4011

dataman start

#simulator start -s -u $simulator_udp_port
#tone_alarm start
#gyrosim start
#accelsim start
#barosim start
#gpssim start
#sensors start
#commander start

udp_gcs_port_local=$((14556+px4_instance))
mavlink start -x -u $udp_gcs_port_local -r 4000000
mavlink stream -r 50 -s POSITION_TARGET_LOCAL_NED -u $udp_gcs_port_local
mavlink stream -r 50 -s LOCAL_POSITION_NED -u $udp_gcs_port_local
mavlink stream -r 50 -s GLOBAL_POSITION_INT -u $udp_gcs_port_local
mavlink stream -r 50 -s ATTITUDE -u $udp_gcs_port_local
mavlink stream -r 50 -s ATTITUDE_QUATERNION -u $udp_gcs_port_local
mavlink stream -r 50 -s ATTITUDE_TARGET -u $udp_gcs_port_local
mavlink stream -r 50 -s SERVO_OUTPUT_RAW_0 -u $udp_gcs_port_local
mavlink stream -r 20 -s RC_CHANNELS -u $udp_gcs_port_local
mavlink stream -r 10 -s OPTICAL_FLOW_RAD -u $udp_gcs_port_local
mavlink boot_complete

